name: Go Proxy Scanning

on:
  workflow_dispatch:
  #schedule:
   # - cron: "0 */6 * * *"  # Jalan setiap 6 jam

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    name: Scan Proxy

    steps:
    - name: 📂 Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GIT_TOKEN }}

    - name: 💾 Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22' # Sesuaikan dengan versi Go kamu

    - name: 📦 Install Go Dependencies
      working-directory: ./SC-Emilia
      run: go mod tidy

    - name: ▶️ Run Go Proxy Scan
      working-directory: ./SC-Emilia
      run: go run main.go

    - name: 📤 Commit and Push Changes
      if: ${{ success() }}
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "🔁 Update proxyip"
        git push origin main --force
